### ISSUE TITLE
Cannot read property 'brand' of undefined

### ISSUE THREAD

**Issue by thg303** [chabokpush/chabok-client-rn-js#1]
I followed the documentation. but after lunch this error shows up in android.
```
react-native-cli: 2.0.1
react-native: 0.50.4

```
minSdkVersion 16
targetSdkVersion 26

**Comment by thg303** [comment]
appearantly this plugin needs "react-native-device-info" and "react-native-push-notification"! why documentation says nothing about this?? it took me 5 hours!

**Comment by behrad** [comment]
> why documentation says nothing about this?? it took me 5 hours!

Our react-native (pureJS) sdk is released recently, and it's documentation is not mature yet.
Thank you for the contribution @thg303 and beg our apology for your spent time ❤️ 

@jalalazimi @Husseinhj Update docs accordingly.

**Comment by thg303** [comment]
by the way, I wonder why the code is minified? this is github, you may use people contributions, that's one of the best part of open source paradigm after all.

**Comment by behrad** [comment]
> by the way, I wonder why the code is minified? this is github, you may use people contributions, that's one of the best part of open source paradigm after all.

You're right @thg303 However there are some business considerations for us now. We may push the clear readable code in future :)

**Comment by behrad** [comment]
Closing since this is fixed. You can re-open anytime.
