### ISSUE TITLE
can not read property 'appVersion' of undefined

### ISSUE THREAD

**Issue by farzansalimian** [chabokpush/chabok-client-rn-js#2]
Hey there,
i followed the document but when i try to run the app this error show up
![img-20180912-wa0009](https://user-images.githubusercontent.com/33595936/45429513-b6af9c80-b6b8-11e8-8e16-c05021ee583c.jpg)

**Comment by amir-yaghoubi** [comment]
Hi,
Did you follow [installation guides](https://doc.chabokpush.com/react-native/installation.html)?
and did you run react link?
```
react-native link
```
This error is occur when **chabok sdk** cannot require `react-native-device-info` module.
so please make sure `npm install chabokpush-rn` and dependencies are successful.
after that run `react-native link` so modules can load properly.

**Comment by farzansalimian** [comment]
@amir-yaghoobi 
thanx it fix the error
but another one showed up
![screenshot_20180912-204424](https://user-images.githubusercontent.com/33595936/45438670-fc766000-b6cc-11e8-8d3f-2bbb47baf99f.png)

**Comment by amir-yaghoubi** [comment]
@farzansalimian 
please replace
```javascript
const chabok = new chabokpush.Chabok(auth, config)
```
with:
```javascript
const chabok = new chabokpush(auth, config)
```

That way of initializing is for our [javascript sdk](https://github.com/chabokpush/chabok-client-js) and not for react native. we will update our documentation.

**Comment by farzansalimian** [comment]
@amir-yaghoobi 
i changed it but it does not fix the error

![screenshot_20180913-025940](https://user-images.githubusercontent.com/33595936/45456831-7c1e2200-b701-11e8-9d3a-0014e5f3a67f.png)

**Comment by behrad** [comment]
Send your code snippet hear @farzansalimian

**Comment by farzansalimian** [comment]
@behrad 

```js
import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
//import Pushe from 'react-native-pushe'

import LoginScreen from "./screens/login/index";
import SignupScreen from "./screens/signup/index";
import Activate from "./screens/activate/index";
import DrawerHomeScreenRouter from "./src/index.js";

import SideBar from "./src/SideBar/SideBar.js";
import { I18nManager } from 'react-native';
import RNRestart from 'react-native-restart';

var chabokpush = require('chabokpush-rn');

const auth = {
  appId: '***',
  apiKey: '***',
  username: '***',
  password: '***',
  devMode:true
}
const options = {
      silent: false,
      realtime: true
    };
const chabok = new chabokpush.Chabok(auth, options)

import { StackNavigator, SwitchNavigator, DrawerNavigator } from "react-navigation";
const AppStack = DrawerNavigator({
  drawer1: {
    screen: DrawerHomeScreenRouter,
}
},
  {
    headerMode: 'none',
    navigationOptions: {
      headerVisible: false,
    },
    drawerPosition: 'right',
    contentComponent: props => <SideBar {...props} />
  });
const AuthStack = StackNavigator(
  {
    Login: LoginScreen,
    Signup: SignupScreen,
    Activate: Activate
  },
  {
    headerMode: 'none',
    navigationOptions: {
      headerVisible: false,
    },
    drawerPosition: 'right',
  }
);
const HomeScreenRouter = SwitchNavigator(
  {
    App: AppStack,
    Auth: AuthStack,
  },

  {
    headerMode: 'none',
    navigationOptions: {
      headerVisible: false,
    },
    initialRouteName: 'Auth',
  }
);


export default class App extends Component {
  constructor(props) {
    super(props);
    I18nManager.forceRTL(true);
    if (!I18nManager.isRTL) {
      RNRestart.Restart();
    }

    //Pushe.initialize(true);
    this.chabok.setPushNotificationToken("TOKEN")
    chabok.register('USER_ID')

  }
  render() {
    return (
      <HomeScreenRouter />
    );
  }
}
```

**Comment by amir-yaghoubi** [comment]
It's seems you have to install `react-native-device-info` as your dependency in order to **chabok** sdk can work properly. so after all above steps, run:
```bash
npm install --save react-native-device-info
```
Then run **react-native** link, so **chabok** can use this dependency

```bash
react-native link react-native-device-info
```

and for initializing **chabok**:
```javascript
const chabok = new chabokpush(auth, options)
```

**Comment by farzansalimian** [comment]
@amir-yaghoobi 
i have already installed and linked react-native-device-info but i did it again.i still get the same error

**Comment by amir-yaghoubi** [comment]
After linking you have to reinstall app. (reloading js bundle does not affect)
```
react-native run-android
// or
react-native run-ios
```

**Comment by amir-yaghoubi** [comment]
### Sample scenario
I just created a fresh react-native app with `react-native init sample`, then i configured android as documents said (added permission and receiver in `androidManifest.xml`),
then:
```
npm install
npm install chabokpush-rn --save
npm install react-native-device-info --save
react-native link chabokpush-rn
react-native link react-native-device-info
```
In `App.js` I added these lines:
```javascript
import chabokpush from 'chabokpush-rn'

const auth = {
 appId: 'APP_ID',
 apiKey: 'API_KEY',
 username: 'USERNAME',
 password: 'PASSWORD',
 devMode:true
}
const options = {
 silent: false,
 realtime: true
};
const chabok = new chabokpush(auth, options)

chabok.register('USER_ID')
```
in the end `react-native run-android`. and app started without any errors

I hope this helps you

**Comment by farzansalimian** [comment]
@amir-yaghoobi 
reinstalling chabokpush-rn solve the problem
thanks

**Comment by amir-yaghoubi** [comment]
Your welcome,
since this problem is solved, I am going to close this issue

**Comment by behrad** [comment]
Please update docs if needed @amir-yaghoobi
