### ISSUE TITLE
ios notification on production does not work

### ISSUE THREAD

**Issue by farzansalimian** [chabokpush/chabok-client-rn-js#3]
Hey there,
sending notification perfectly works in development but when i deploy app on sibapp.com users register on chabok panel but sending  notification does not work. after short time of each register the users token become invalid. what should i do?
thanks in advance

**Comment by Husseinhj** [comment]
The `INVALID` error in Chabok means that your push notification settings do not match the provision profile that you got with the release IPA.
Please, check that you have used the correct `bundleId`, **p8** or [**pem** file](https://doc.chabokpush.com/ios/certificate.html).

**Comment by farzansalimian** [comment]
@Husseinhj
thank you it solved my problem
