### ISSUE TITLE
عدم دریافت پوش نوتیفیکیشن در برنامه ی اندرویدی

### ISSUE THREAD

**Issue by zeoses** [chabokpush/chabok-client-rn-js#4]
> 
https://github.com/chabokpush/chabok-panel/issues/8#issuecomment-438941103
> 

من کانفیک های مربوطه رو انجام دادم ولی در برنامه هیچ نوتیفکیشینی در نکرده ام.. .

**Comment by Husseinhj** [comment]
<p dir="rtl">آیا تنظیمات <a href="https://doc.chabokpush.com/react-native/push-notification.html#%D8%A7%D9%86%D8%AF%D8%B1%D9%88%DB%8C%D8%AF">نوتیفیکیشن اندروید</a> و <a href="https://doc.chabokpush.com/react-native/push-notification.html#%D8%A2%DB%8C%D8%A7%D9%88%D8%A7%D8%B3">iOS</a> را انجام داده‌اید؟</p>
<p dir="rtl">آیا توکن پوش نوتیفیکیشن را پس از دریافت از کتابخانه <a href="https://doc.chabokpush.com/react-native/installation.html">react-native-push-notification</a> به چابک <a href="https://doc.chabokpush.com/react-native/setup.html#%D9%85%D8%AA%D8%AF-%D8%A7%D9%81%D8%B2%D9%88%D8%AF%D9%86-%D8%AA%D9%88%DA%A9%D9%86-%D8%A8%D8%B1%D8%A7%DB%8C-%D8%A7%D8%B1%D8%B3%D8%A7%D9%84-%D9%BE%D9%88%D8%B4">همانند مستندات</a> داده‌اید؟</p>
<p dir="rtl">برای بررسی دقیق‌تر<a href="https://github.com/chabokpush/chabok-starter-rn-js"> پروژه استارتر</a> چابک را مشاهده کنید و از پیاده‌سازی آن استفاده کنید.</p>

**Comment by zeoses** [comment]
> آیا تنظیمات [نوتیفیکیشن اندروید](https://doc.chabokpush.com/react-native/push-notification.html#%D8%A7%D9%86%D8%AF%D8%B1%D9%88%DB%8C%D8%AF) و [iOS](https://doc.chabokpush.com/react-native/push-notification.html#%D8%A2%DB%8C%D8%A7%D9%88%D8%A7%D8%B3) را انجام داده‌اید؟
> 
> آیا توکن پوش نوتیفیکیشن را پس از دریافت از کتابخانه [react-native-push-notification](https://doc.chabokpush.com/react-native/installation.html) به چابک [همانند مستندات](https://doc.chabokpush.com/react-native/setup.html#%D9%85%D8%AA%D8%AF-%D8%A7%D9%81%D8%B2%D9%88%D8%AF%D9%86-%D8%AA%D9%88%DA%A9%D9%86-%D8%A8%D8%B1%D8%A7%DB%8C-%D8%A7%D8%B1%D8%B3%D8%A7%D9%84-%D9%BE%D9%88%D8%B4) داده‌اید؟
> 
> برای بررسی دقیق‌تر[ پروژه استارتر](https://github.com/chabokpush/chabok-starter-rn-js) چابک را مشاهده کنید و از پیاده‌سازی آن استفاده کنید.

> 

 بله مستندات و کار هایی رو که باید انجام دادم حتی برنامه هم توسط سایت شناسایی و تایید شد ولی بازم هم همین مسئله است و بنده اون وارنیگ رو به جای نوتیفیکشن مشاهده می کنم .. .

![untitled](https://user-images.githubusercontent.com/15188675/48539404-4269c300-e8cc-11e8-9d29-31dfaaf4b1ff.png)

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">بله مستندات و کار هایی رو که باید انجام دادم حتی برنامه هم توسط سایت شناسایی و تایید شد ولی بازم هم همین مسئله است و بنده اون وارنیگ رو به جای نوتیفیکشن مشاهده می کنم .. .</p>
</blockquote>
<p dir="rtl">آمدن دستگاه در پنل به معنی دریافت نوتیفیکیشن نیست (شما در حال حاضر فقط می‌توانید پیام چابک را دریافت کنید)، زمانی که شما توکن پوش‌نوتیفیکیشن را که در مستندات ذکر شده را به چابک دهید، می‌توانید پوش‌نوتیفیکیشن دریافت کنید.</p>
<p dir="rtl"><a href="https://github.com/chabokpush/chabok-starter-rn-js">پروژه استارتر</a> را مشاهده کرده‌اید؟</p>
<p dir="rtl">خطا <code>disable</code> به این معنی است که هنوز توکنی برای این دستگاه ست نشده است</p>

**Comment by zeoses** [comment]
> > بله مستندات و کار هایی رو که باید انجام دادم حتی برنامه هم توسط سایت شناسایی و تایید شد ولی بازم هم همین مسئله است و بنده اون وارنیگ رو به جای نوتیفیکشن مشاهده می کنم .. .
> 
> آمدن دستگاه در پنل به معنی دریافت نوتیفیکیشن نیست (شما در حال حاضر فقط می‌توانید پیام چابک را دریافت کنید)، زمانی که شما توکن پوش‌نوتیفیکیشن را که در مستندات ذکر شده را به چابک دهید، می‌توانید پوش‌نوتیفیکیشن دریافت کنید.
> 
> [پروژه استارتر](https://github.com/chabokpush/chabok-starter-rn-js) را مشاهده کرده‌اید؟

بله کار ها رو متناسب با چیزی که در پروژه ی استارت انجام داده بودین انجام دادم 
و تنها چیزی که متفاوت هست قسمت مربوط به قسمت برنامه است و در قسمت زیر برای شما ارسال کردم فک می کنم که اشکال از قسمت زیر باشه .
```

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View, Button, AppState, AsyncStorage } from 'react-native';
import chabokpush from 'chabokpush-rn';

var PushNotification = require('react-native-push-notification');

const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' + 'Cmd+D or shake for dev menu',
  android:
    'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});


const auth = {
  appId: 'my-app-id',
  apiKey: 'my-key',
  username: 'my-user',
  password: 'my-pass',
  devMode: true
}
const options = {
  silent: false,
  realtime: true
};
this.chabok = new chabokpush(auth, options);

PushNotification.configure({
  onRegister: ({ token }) => {
    if (token) {
      this.chabok.setPushNotificationToken(token)
    }
  },
  // (required) Called when a remote or local notification is opened or received
  onNotification: function (notification) {
    console.warn('NOTIFICATION:', notification);
    // required on iOS only (see fetchCompletionHandler docs: https://facebook.github.io/react-native/docs/pushnotificationios.html)
    notification.finish(PushNotificationIOS.FetchResult.NoData);
  },
  senderID: "My-GCM Sender ID", // ANDROID ONLY: (optional) GCM Sender ID.
  permissions: {
    alert: true,
    badge: true,
    sound: true
  },
  popInitialNotification: true,
  requestPermissions: true,
});

type Props = {};
export default class App extends Component<Props> {

  state = {
    chabokStatus: 'offline',
    messages: [],
    phone: 'my id',
    currentUser: 'xs',
    newUser: '',
    archive: {},
    users: [],
    modalVisible: false,
    userPromptVisible: false,
    appState: AppState.currentState
  }



 
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <Text style={styles.instructions}>{this.state.currentUser}</Text>
        <Text style={styles.instructions}>{instructions}</Text>
        <Button
          title="vvvv"

          onPress={() => {
            var i = 1;
            if (i == 1) {

              chabok.register(this.state.phone);
              i = i + 1;
              if (chabok.isRegistered()) {

                this.setState({
                  currentUser: "dds"
                })

               
              }
            }

          }} />


      </View>
    );
  }
}

```

**Comment by Husseinhj** [comment]
@zeoses آیا مشکل شما حل شده است؟

**Comment by zeoses** [comment]
بله ممنون ...
فقط یه سوال مستندات دیگری دارین که به بنده کمک کنه که در حالتی که برنامه بسته است نوتیف دریافت نمایم ...؟

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">فقط یه سوال مستندات دیگری دارین که به بنده کمک کنه که در حالتی که برنامه بسته است نوتیف دریافت نمایم</p>
</blockquote>
<p dir="rtl"> برای دریافت پوش‌نوتیفیکشن در حالتی که اپلکیشن بسته است باید با استفاده از <a href="https://doc.chabokpush.com/react-native/push-notification.html#%D8%A7%D9%86%D8%AF%D8%B1%D9%88%DB%8C%D8%AF">مواردی که در مستندات آمده را پیاده‌سازی کنید</a>، چون کتابخانه فوق برای پشتیبانی از کد پوش هیچ گونه کد نیتوی در آن قرار داده نشده است.</p>
<p dir="rtl">اگر از کد پوش استفاده نمی‌کنید توصیه ما این است که از کتابخانه <a href="https://doc.chabokpush.com/react-native-bridge/required.html">bridge ریکت نیتو</a> چابک استفاده کنید که از کتابخانه نیتیو اندروید و iOS استفاده می‌کند</p>

**Comment by zeoses** [comment]
بازم ممنون از راهنماییتون تو برنامه ام به کدپوش وابسطه است 
یه بار دیگه مستندات رو بررسی می کنم چون من در حالت بسته بودن برنامه نوتیفکشنی دریافت نمی کنم .. 
و اینکه در حالتی که دستگاه در سایت آفلاین هست آیا پیغام ارسال می شه... ؟

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">بازم ممنون از راهنماییتون تو برنامه ام به کدپوش وابسطه است </p>
</blockquote>
<p dir="rtl">خواهش می‌کنم.</p>
<blockquote dir="rtl">
<p dir="rtl">و اینکه در حالتی که دستگاه در سایت آفلاین هست آیا پیغام ارسال می شه... ؟</p>
</blockquote>
<p dir="rtl">پیام چابک زمانی که اپلیکیشن باز باشد (به چابک متصل باشد) حتما پیام را در همان لحظه دریافت می‌کند</p>
<p dir="rtl">در صورت عدم اتصال به چابک (بسته بودن اپ) چابک برای آن کاربر اقدام به ارسال نوتیفیکیشن می‌کند (در صورت قرار دادن توکن پوش)</p>

**Comment by Husseinhj** [comment]
<p dir="rtl">@zeoses 
برای دستگاه‌های اندروید شما خطای <a href="https://doc.chabokpush.com/android/troubleshoot.html#%D8%AF%D8%B1-%D8%AD%D8%A7%D9%84%D8%AA-%D8%A8%D8%B3%D8%AA%D9%87-%D8%A8%D9%88%D8%AF%D9%86-%D8%A7%D9%BE-%D9%BE%DB%8C%D8%A7%D9%85-%DA%86%D8%A7%D8%A8%DA%A9-%D8%AF%D8%B1%DB%8C%D8%A7%D9%81%D8%AA-%D9%86%D9%85%DB%8C%D8%B4%D9%88%D8%AF-%D9%81%D9%82%D8%B7-%D9%86%D9%88%D8%AA%DB%8C%D9%81%DB%8C%DA%A9%DB%8C%D8%B4%D9%86-%D8%AF%D8%B1%DB%8C%D8%A7%D9%81%D8%AA-%D8%AE%D9%88%D8%A7%D9%87%D8%AF-%D8%B4%D8%AF">SENDER_ID_MISMATCH</a> را می‌گیرید</p>
