### ISSUE TITLE
مشکل ارسال همزمان 2 پوش به کاربر

### ISSUE THREAD

**Issue by amirsorayaei** [chabokpush/chabok-client-rn-js#7]
سلام من زمانی که میخوام از سمت پنل به کاربر تست نوتیفیکیشن ارسال کنم، دوتا نوتیفیکیشن کاربر دریافت میکنه
خواستم ببینم مشکل از چیه چرا باید دوبار ارسال بشه...!!!

**Comment by behrad** [comment]
این مشکل تلفنی حل شد
