### ISSUE TITLE
عدم اتصال به سرویس چابک

### ISSUE THREAD

**Issue by coyot1904** [chabokpush/chabok-client-rn-js#8]
<p dir="rtl">سلام</p>
<p dir="rtl">من دوتا مشکل عجیب دارم قبلا با سرویس رایگان شما کار کردم به راحتی وصل شد و کار کردم 
الان نسخه ریکت نیتو ۶ رو دارم
و کلا نسخه رو نسخه پولی تغییر دادیم ولی با همه تفاصیر کلا وصل نمیشم به سیستم شما
و مرتب پیام disconnetedدارم</p>
<p dir="rtl">ضمن اینکه </p>
<pre><code>get connection info is undefined android</code></pre><p dir="rtl">هم مرتب برام ارسال میشه ممکنه راهنمایی بفرمایید</p>

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">الان نسخه ریکت نیتو ۶ رو دارم</p>
</blockquote>
<p dir="rtl">به تازگی روی این نسخه مهاجرت کردید؟</p>
<blockquote dir="rtl">
<p dir="rtl">و کلا نسخه رو نسخه پولی تغییر دادیم ولی با همه تفاصیر کلا وصل نمیشم به سیستم شما
و مرتب پیام disconnetedدارم</p>
</blockquote>
<p dir="rtl">آیا کلیدهای پنل عملیاتی رو توی کدتو قرار دادید؟
مقدار devMode رو به false تغییر دادید؟</p>
<p dir="rtl">در صورت مشاهده خطا در اتصال، متن خطا رو برای ما اینجا قرار بدید.</p>
<blockquote dir="rtl">
<p dir="rtl">ضمن اینکه
get connection info is undefined android</p>
</blockquote>
<p dir="rtl">از کدام نسخه کتابخانه چابک و نسخه کتابخانه deviceInfo استفاده می‌کنید؟</p>

**Comment by coyot1904** [comment]
`  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
      Memory: 79.07 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 26, 27, 28, 29
        Build Tools: 28.0.2, 28.0.3, 29.0.1
        System Images: android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.2 => 0.59.2 
    npmGlobalPackages:
      react-native-cli: 2.0.1
`

وقتی دستور 
npm install react-native-push-notification --save


و بعد
react-native rund-android 
رو اجرا میکنم 
> Task :react-native-push-notification:compileDebugJavaWithJavac FAILED
/Users/keyvan/Desktop/sib/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java:21: error: cannot find symbol
import android.support.v4.app.NotificationCompat;
                             ^
  symbol:   class NotificationCompat
  location: package android.support.v4.app
/Users/keyvan/Desktop/sib/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationAttributes.java:4: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/keyvan/Desktop/sib/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationAttributes.java:120: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class RNPushNotificationAttributes
/Users/keyvan/Desktop/sib/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/ReactNativePushNotificationPackage.java:20: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/keyvan/Desktop/sib/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java:160: error: package NotificationCompat does not exist
            NotificationCompat.Builder notification = new NotificationCompat.Builder(context)
                              ^
/Users/keyvan/Desktop/sib/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java:164: error: cannot find symbol
                    .setPriority(NotificationCompat.PRIORITY_HIGH)
                                 ^
  symbol:   variable NotificationCompat
  location: class RNPushNotificationHelper
/Users/keyvan/Desktop/sib/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java:163: error: cannot find symbol
                    .setVisibility(NotificationCompat.VISIBILITY_PRIVATE)
                                   ^
  symbol:   variable NotificationCompat
  location: class RNPushNotificationHelper
/Users/keyvan/Desktop/sib/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java:160: error: package NotificationCompat does not exist
            NotificationCompat.Builder notification = new NotificationCompat.Builder(context)
                                                                            ^
/Users/keyvan/Desktop/sib/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java:225: error: package NotificationCompat does not exist
            notification.setStyle(new NotificationCompat.BigTextStyle().bigText(bigText));
                                                        ^
/Users/keyvan/Desktop/sib/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java:261: error: cannot find symbol
                notification.setCategory(NotificationCompat.CATEGORY_CALL);
                                         ^
  symbol:   variable NotificationCompat
  location: class RNPushNotificationHelper
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
10 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-push-notification:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

این خطا رو دارم

**Comment by coyot1904** [comment]
> > الان نسخه ریکت نیتو ۶ رو دارم
> 
> به تازگی روی این نسخه مهاجرت کردید؟
> 
> > و کلا نسخه رو نسخه پولی تغییر دادیم ولی با همه تفاصیر کلا وصل نمیشم به سیستم شما
> > و مرتب پیام disconnetedدارم
> 
> آیا کلیدهای پنل عملیاتی رو توی کدتو قرار دادید؟ مقدار devMode رو به false تغییر دادید؟
> 
> در صورت مشاهده خطا در اتصال، متن خطا رو برای ما اینجا قرار بدید.
> 
> > ضمن اینکه
> > get connection info is undefined android
> 
> از کدام نسخه کتابخانه چابک و نسخه کتابخانه deviceInfo استفاده می‌کنید؟

کلا کتابخانه push notification روی نسخه ۰.۶۰ کار نیمکنه موقع خروجی نوشته اینو واسه همین نسخه رو آوردم پایین

**Comment by Husseinhj** [comment]
<p dir="rtl">این موضوع مربوط به کتابخانه <code>react-native-push-notification</code> هست.</p>
<p dir="rtl"><a href="https://dev.to/bdbch/how-to-get-react-native-push-notifications-to-work-with-react-native-0-60-e20">در این بلاگ</a> در مورد استفاده از این کتابخانه در نسخه ریکت نیتیو ۶۰ توضیح داده شده.</p>
